// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5828.RoboPats.subsystems;

import org.usfirst.frc5828.RoboPats.Robot;
import org.usfirst.frc5828.RoboPats.RobotMap;
import org.usfirst.frc5828.RoboPats.commands.*;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Arm extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController speedController1 = RobotMap.armSpeedController1;
    private final SpeedController nULL = RobotMap.armNULL;
    private final RobotDrive armControl = RobotMap.armArmControl;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void armUp(){
    	Robot.arm.takeJoystickInputs(Robot.oi.xbox.getRawButton(5));
    	speedController1.set(0.6);
    }
    
    public void takeJoystickInputs(boolean rawButton) {
		// TODO Auto-generated method stub
		
	}

	public void armDown(){
		Robot.arm.takeJoystickInputs(Robot.oi.xbox.getRawButton(6));
    	speedController1.set(-0.6);
    }
    
    public void armStop(){
    	speedController1.set(0.0);
		
	}

	public Object takeJoystickInputs(double rawAxis) {
		// TODO Auto-generated method stub
		return null;
	}

}

