// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5828.RoboPats.subsystems;

import org.usfirst.frc5828.RoboPats.Robot;
import org.usfirst.frc5828.RoboPats.RobotMap;
import org.usfirst.frc5828.RoboPats.commands.*;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.TalonSRX;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Cannon extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController speedController1 = RobotMap.cannonSpeedController1;
    private final SpeedController speedController2 = RobotMap.cannonSpeedController2;
    private final RobotDrive cannonMotors = RobotMap.cannonCannonMotors;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    	        // Set the default command for a subsystem here.
    	        // setDefaultCommand(new MySpecialCommand());
    	    }
    public void fire() {
    	Robot.cannon.speedController1.set(.8);
    	Robot.cannon.speedController2.set(0);
    }
    	    
    public void stop() {
    	Robot.cannon.speedController1.set(0);
    	Robot.cannon.speedController2.set(0);
    }
				
}
    	

 
