// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5828.RoboPats;

import org.usfirst.frc5828.RoboPats.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

import org.usfirst.frc5828.RoboPats.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    public static final String Xbox = null;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton joystickButton1;
    public JoystickButton joystickButton2;
    public JoystickButton joystickButton3;
    public JoystickButton joystickButton4;
    public Joystick xbox;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        xbox = new Joystick(0);
        
        joystickButton4 = new JoystickButton(xbox, 6);
        joystickButton4.whileHeld(new armDown(-.3));
        joystickButton3 = new JoystickButton(xbox, 5);
        joystickButton3.whileHeld(new armUp(.3));
        joystickButton2 = new JoystickButton(xbox, 1);
        joystickButton2.whileHeld(new DriveManual());
        joystickButton1 = new JoystickButton(xbox, 5);
        joystickButton1.whileHeld(new DriveManual());


        // SmartDashboard Buttons
        SmartDashboard.putData("ChevaldeFriseAuto", new ChevaldeFriseAuto());
        SmartDashboard.putData("DrawBridgeAuto", new DrawBridgeAuto());
        SmartDashboard.putData("LowBarAuto", new LowBarAuto());
        SmartDashboard.putData("armDownAuto", new armDownAuto());
        SmartDashboard.putData("armUpAuto", new armUpAuto());
        SmartDashboard.putData("DriveForwardHalfAuto", new DriveForwardHalfAuto());
        SmartDashboard.putData("DriveReverseHalfAuto", new DriveReverseHalfAuto());
        SmartDashboard.putData("Drive ForwardAuto", new DriveForwardAuto());
        SmartDashboard.putData("DriveManual", new DriveManual());
        SmartDashboard.putData("armUp: armUp", new armUp(.5));
        SmartDashboard.putData("armDown: armDown", new armDown(-.5));
        SmartDashboard.putData("Drive ReverseAuto", new DriveReverseAuto());
        SmartDashboard.putData("AutoGroup", new AutoGroup());
        SmartDashboard.putData("AutoCommand", new AutoCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getXbox() {
        return xbox;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

